# Colors referenced from:
# https://material-foundation.github.io/material-theme-builder

[colors]
0 = "000000"
5 = "190e0b"
10 = "251915"
15 = "30231f"
20 = "3b2d29"
25 = "473834"
30 = "53433f"
35 = "5f4f4a"
40 = "6c5b56"
50 = "85736e"
60 = "a08c87"
70 = "bca7a1"
80 = "d8c2bc"
90 = "f5ded8"
95 = "ffede8"
98 = "fff8f6"
99 = "fffbff"
100 = "ffffff"
error = "ba1a1a"

[fonts]
sans = "IBM Plex Sans"
serif = "IBM Plex Serif"
mono = "FiraCode Nerd Font"
